### ISSUE TITLE
Building a book fails without gatsby actively serving

### ISSUE THREAD

**Issue by fyodorio** [SaraVieira/gatsby-starter-book#13]
Hi @SaraVieira,

First of all, thanks for this awesome project 👍

I'd tried to play with it and build a book. Node failed with errors mentioning that `localhost:8000` is not found.

So I'd run the serve command for gatsby and then re-run the build command - and it succeeded.

What I suggest is to add the note about this _(necessary, I believe, if it's intended behaviour)_ pre-build part of the flow. Or add the prebuild script as an alternative.

Please let me know what you think about it, I can submit a PR with the most suitable option.

**Comment by SaraVieira** [comment]
Hey!

Thank you so much for making an issue, seems many people felt confused about it so I wrote some new docs that add that and many other small quirks at https://saravieira.github.io/starter-book/#/ and added that to the readme.

I'm gonna close this since it's now there but again thank you for raising this
